const POPULAR_TITLES = [
  "The Godfather",
  "The Godfather Part II",
  "The Dark Knight",
  "Interstellar",
  "Inception",
  "The Matrix",
  "Pulp Fiction",
  "Fight Club",
  "Forrest Gump",
  "The Shawshank Redemption",
  "The Lord of the Rings",
  "Star Wars",
  "The Empire Strikes Back",
  "Raiders of the Lost Ark",
  "Jaws",
  "Alien",
  "Terminator",
  "Back to the Future",
  "Jurassic Park",
  "Titanic",
  "Avatar",
  "Oppenheimer",
  "Parasite",
  "Spirited Away",
  "The Shining",
  "Goodfellas",
  "Se7en",
  "Whiplash",
  "Gladiator",
  "Mad Max: Fury Road",
  "Blade Runner",
  "Blade Runner 2049",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "The Truman Show",
  "La La Land",
  "Casablanca",
  "Citizen Kane",
  "Seven Samurai",
  "2001: A Space Odyssey",
  "Psycho",
  "Chinatown",
  "Toy Story",
  "Toy Story 2",
  "Spider-Man: Into the Spider-Verse",
  "Coco",
  "Get Out",
  "No Country for Old Men",
  "Dune",
  "Dune: Part Two",
  "The Batman",
  "The Avengers",
  "Avengers: Endgame",
  "Spider-Man: No Way Home",
  "The Super Mario Bros. Movie",
  "Top Gun: Maverick",
  "Mission Impossible",
  "Knives Out",
  "The Princess Bride",
  "Harry Potter and the Sorcerer's Stone",
  "Harry Potter and the Deathly Hallows",
  "The Lion King",
  "WALL-E",
  "Breaking Bad",
  "Better Call Saul",
  "Game of Thrones",
  "House of the Dragon",
  "The Last of Us",
  "Fallout",
  "The Boys",
  "Stranger Things",
  "The Sopranos",
  "The Wire",
  "Chernobyl",
  "Sherlock",
  "Dark",
  "Arcane",
  "Attack on Titan",
  "One Piece",
  "Peaky Blinders",
  "Narcos",
  "Black Mirror",
  "The Office",
  "Friends",
  "The Mandalorian",
  "Loki",
  "Daredevil",
  "Invincible",
  "The Bear",
  "Rick and Morty",
  "Band of Brothers",
  "Severance",
  "Squid Game",
  "Money Heist",
  "The Simpsons",
];

export const getRandomPopularTitle = (excludeTitle = "") => {
  const normalizedExclude = excludeTitle.trim().toLowerCase();
  const options = POPULAR_TITLES.filter(
    (title) => title.toLowerCase() !== normalizedExclude,
  );

  const source = options.length > 0 ? options : POPULAR_TITLES;
  const randomIndex = Math.floor(Math.random() * source.length);

  return source[randomIndex];
};
